config/routes.rb
Rails.application.routes.draw do
  root 'trackers#index'
  resources :trackers, only: [:index, :show, :create], param: :token
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tracker.rb
class Tracker < ApplicationRecord
  has_many :tracker_hits, dependent: :destroy

  before_create do
    self.token = SecureRandom.uuid
  end

  def touch(ip: nil)
    self.tracker_hits.create(ip: ip)
  end
end

app/models/tracker_hit.rb
class TrackerHit < ApplicationRecord
  belongs_to :tracker
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trackers_controller.rb
Mime::Type.register 'image/jpg', :jpg
Mime::Type.register 'image/png', :png
Mime::Type.register 'image/webp', :webp

class TrackersController < ApplicationController
  EMPTY_PNG = Base64.decode64('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=')

  def index
    @trackers = Tracker.all
  end

  def show
    @tracker = Tracker.includes(:tracker_hits).find_by(token: params[:token])

    respond_to do |format|
      format.html do
        @base_url = request.base_url
      end
      format.any(:jpg, :png, :webp) do
        @tracker.touch(ip: request.ip)
        render plain: nil
      end
    end
  end

  def create
    @tracker = Tracker.create

    redirect_to tracker_url(@tracker.token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SneakyPixel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="repo-link">
      <%= link_to "https://gitlab.com/image-bouncing/sneaky-pixel", target: '_blank' do %>
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/GitLab_Logo.svg/1200px-GitLab_Logo.svg.png" alt="Gitlab logo" />
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/trackers/_tracker.html.erb
<li><%= link_to tracker.token, tracker_path(token: tracker.token) %></li>

app/views/trackers/_tracker_embed_source.html.erb
<div data-controller="clipboard">
  <p>Embed the HTML below into an email to seed the email with a tracker. You'll then be able to check back here to see when the email is opened and the IP address associated with the client.</p>
  <textarea data-target="clipboard.source" cols=60 rows=2 readonly><img src="<%= base_url %>/trackers/<%= token %>.jpg" style="height:0; width:0;" /></textarea>
  <button data-action="clipboard#copy" class="clipboard-button">Copy Embed</button>
</div>

app/views/trackers/_tracker_hit.html.erb
<li><%= tracker_hit.ip %> <%= time_ago_in_words tracker_hit.created_at %> ago</li>

app/views/trackers/index.html.erb
<h1>Trackers</h1>
<p><%= link_to 'Create new', trackers_path, method: 'POST' %></p>
<ul><%= render partial: 'tracker', collection: @trackers %></ul>

app/views/trackers/show.html.erb
<p><%= link_to 'Back', trackers_url %></p>
<h1>Tracker <%= @tracker.token %></h1>
<%= render partial: 'tracker_embed_source', locals: { base_url: @base_url, token: @tracker.token } %>
<h2>Hits</h2>
<% if @tracker.tracker_hits.size > 0 %>
<ul><%= render partial: 'tracker_hit', collection: @tracker.tracker_hits %></ul>
<% else %>
<p>No hits yet</p>
<% end %>